# book-service-local.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: local_user
    password: local_password

  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
