# discovery-server-docker.yml

spring:
  profiles: docker

  eureka:
    instance:
      hostname: discovery-server  # Ensures hostname matches Docker service name

server:
  port: 8761  # Ensures the port remains consistent


