server:
  port: 8761

spring:
  application:
    name: discovery-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
  server:
    enable-self-preservation: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:discovery-server}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework: WARN
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
