# gateway-service-local.yml

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000" # Override if necessary
  eureka:
    client:
      service-url:
        defaultZone: "http://localhost:8761/eureka/"
      register-with-eureka: false
      fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
