server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${GATEWAY_CORS_ALLOWED_ORIGINS:http://localhost:3000}" # Default to localhost for development
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
    stream:
      bindings: # Placeholder for stream bindings (optional)
        # Define any stream bindings if necessary

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: "${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}"
    register-with-eureka: "${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}"
    fetch-registry: "${EUREKA_CLIENT_FETCH_REGISTRY:true}"
  instance:
    hostname: "${EUREKA_INSTANCE_HOSTNAME:gateway-service}" # Changed from book-service
    prefer-ip-address: "${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework: WARN
      kafka: INFO
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
