# gateway-service-docker.yml

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${GATEWAY_CORS_ALLOWED_ORIGINS:http://localhost:3000}" # Adjust if necessary
  eureka:
    client:
      service-url:
        defaultZone: "http://discovery-server:8761/eureka/"
      register-with-eureka: true
      fetch-registry: true
    instance:
      hostname: gateway-service
      prefer-ip-address: true

# Additional Docker-specific configurations can be added here
