# C:/Users/spenc/Desktop/SpringConfigGit/inventory-service.yml

# Server Configuration
server:
  port: 8083

# Application Name
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    stream:
      bindings:
        bookDeleted-out-0:
          destination: book-deleted-topic
          contentType: application/json
        branchDeleted-out-0:
          destination: branch-deleted-topic
          contentType: application/json

# Eureka Client Configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: inventory-service
    prefer-ip-address: true

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework: WARN
      springframework.kafka: INFO
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
