# C:/Users/spenc/Desktop/SpringConfigGit/inventory-service.yml

# Server Configuration
server:
  port: 8083

# Application Name
spring:
  application:
    name: inventory-service

# PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://inventorydb:5432/inventory
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

# JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Kafka Configuration
  kafka:
    bootstrap-servers: kafka:9092

# Spring Cloud Stream Bindings
  cloud:
    function:
      definition: bookDeleted;branchDeleted
    stream:
      bindings:
        branchDeleted-in-0:
          destination: branch-deleted-topic
          contentType: application/json
        bookDeleted-in-0:
          destination: book-deleted-topic
          contentType: application/json

# Eureka Client Configuration
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: inventory-service
    prefer-ip-address: true

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework: WARN
      springframework.kafka: INFO
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
