# C:/Users/spenc/Desktop/SpringConfigGit/inventory-service-docker.yml

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://inventorydb:5432/inventory
    username: postgres
    password: password
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      bindings:
        branchDeleted-in-0:
          destination: branch-deleted-topic
          contentType: application/json
        bookDeleted-in-0:
          destination: book-deleted-topic
          contentType: application/json

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8761/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: "inventory-service"
    prefer-ip-address: true
