# src/main/resources/location-service-docker.yml

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://locationdb:5432/branches
    username: postgres
    password: password
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      bindings:
        locationDeleted-out-0:
          destination: location-deleted-topic
          contentType: application/json
        branchDeleted-out-0:
          destination: branch-deleted-topic
          contentType: application/json

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: location-service
    prefer-ip-address: true
