# src/main/resources/location-service.yml

server:
  port: 8082

spring:
  application:
    name: location-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  cloud:
    stream:
      bindings:
        bookDeleted-out-0:
          destination: book-deleted-topic
          contentType: application/json
        branchDeleted-out-0:
          destination: branch-deleted-topic
          contentType: application/json

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:location-service}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

# Actuator Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com:
      south: DEBUG
    org:
      springframework:
        WARN: WARN
        kafka: INFO
  file:
    name: /dev/stdout
    max-history: 7
    max-size: 10MB
